/*
 * This source file was generated by the Gradle 'init' task
 */
package _ClassroomNotifier;

import org.junit.jupiter.api.Test;

import classroom.notifier.ClassroomNotifier;

import static org.junit.jupiter.api.Assertions.*;

class ClassroomNotifierTest {

}
