/*
 * This source file was generated by the Gradle 'init' task
 */
package classroom.notifier;

import java.util.HashMap;
import java.util.Map;
import java.util.Observable;

public class ClassroomNotifier extends Observable {
	
	private Map<String, String> AsignacionNueva;
	private Comparador Comparador;
	
	public ClassroomNotifier(String[] args)
	{

	    StartConfig(args);

	    this.AsignacionNueva = new HashMap<String,String>();
	    this.Comparador = new Comparador();

	}
	
	 private void StartConfig(String[] args)
	 {
	     
	 }
	 
	 public Boolean EvaluarDiferencias()
	 {
		 Boolean resultado = false;

	     try
	     {
	         //DataAccess data = Factory.Factory.InstanciarElemento<DataAccess>("DATA");
	         //AsignacionNotificar = data.ListarComisionesNotificar();
	         //Asignacion = data.ListarAulasPorComision();
	         //AsignacionNueva = data.ListarNuevasAulasPorComision();
	    	 AsignacionNueva.put("001", "7010");
	    	 
	    	 //Cargar AsignacionNueva
	         resultado = this.Comparador.ComprobarNovedades(AsignacionNueva);
	     }
	     catch (Exception ex)
	     {
	         resultado = false;
	     }

	     return resultado;

	 }
}
