/*
 * This source file was generated by the Gradle 'init' task
 */
package classroom.notifier;

import classroom.notifier.entity.DataFromFile;
import classroom.notifier.entity.Observable;

public class ClassroomNotifier extends Observable{

	private Notificador Comparador;
	private DataFromFile Database;
	
	public ClassroomNotifier(String[] args)
	{
		super();
	    StartConfig(args);

	}
	
	 private void StartConfig(String[] args)
	 {
		if(args.length > 1) {
			this.Database = new DataFromFile(args[0],args[1]);
		}
		else {
			System.out.printf("No se informo modelo de acceso de datos");
		}
	 }


	 public Notificador getActualizadorMaterias(){
		return this.Comparador;
	 }

}
