/*
 * This source file was generated by the Gradle 'init' task
 */
package classroom.notifier;

import classroom.notifier.entity.Observable;

import java.util.HashMap;
import java.util.Map;

public class ClassroomNotifier extends Observable {
	
	private Map<String, String> AsignacionNueva;
	private Comparador Comparador;
	
	public ClassroomNotifier(String[] args)
	{
		super();
	    StartConfig(args);
	    this.AsignacionNueva = new HashMap<>();
	    this.Comparador = new Comparador();

	}
	
	 private void StartConfig(String[] args)
	 {
		if(args.length > 1) {

		}
	 }
	 
	 public void EvaluarDiferencias()
	 {

	     try
	     {
	         //DataAccess data = Factory.Factory.InstanciarElemento<DataAccess>("DATA");
	         //AsignacionNotificar = data.ListarComisionesNotificar();
	         //Asignacion = data.ListarAulasPorComision();
	         //AsignacionNueva = data.ListarNuevasAulasPorComision();
	    	 AsignacionNueva.put("001", "7010");
	    	 
	    	 //Cargar AsignacionNueva
	         this.Comparador.ComprobarNovedades(AsignacionNueva);
	     }
	     catch (Exception ex)
	     {
			 System.out.println("Error: " + ex);
	     }

	 }
}
