/*
 * This source file was generated by the Gradle 'init' task
 */
package classroom.notifier;

import classroom.notifier.entity.DataFromFile;
import classroom.notifier.entity.Observable;
import classroom.notifier.entity.implement.LecturaDatos;
import classroom.notifier.entity.implement.Observer;

import java.util.HashMap;
import java.util.Map;
public class ClassroomNotifier extends Observable{
	
	private Map<String, String> AsignacionNueva;
	private MateriasActuales Comparador;
	private LecturaDatos Database;
	
	public ClassroomNotifier(String[] args)
	{
		super();
	    StartConfig(args);
	    this.AsignacionNueva = new HashMap<String,String>();
	    this.Comparador = new MateriasActuales(Database);

	}
	
	 private void StartConfig(String[] args)
	 {
		if(args.length > 1) {
			this.Database = new DataFromFile(args[0],args[1]);
		}
	 }
	 
	 public void EvaluarDiferencias()
	 {

	     try
	     {
	         //DataAccess data = Factory.Factory.InstanciarElemento<DataAccess>("DATA");
	         //AsignacionNotificar = data.ListarComisionesNotificar();
	         //Asignacion = data.ListarAulasPorComision();
	         //AsignacionNueva = data.ListarNuevasAulasPorComision();
	    	 AsignacionNueva.put("001", "7010");
	    	 
	    	 //Cargar AsignacionNueva
	         this.Comparador.ComprobarNovedades(AsignacionNueva);
	     }
	     catch (Exception ex)
	     {
			 ex.printStackTrace();
	     }

	 }

	 public MateriasActuales getActualizadorMaterias(){
		return this.Comparador;
	 }

}
